development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://keusnebzlbxtbe:34719e8da55e30a6ea8f94bb13d5140b2d1aa4410db35de9b7db00af2900acdb@ec2-54-163-234-140.compute-1.amazonaws.com:5432/d31hsj48qehc8e
